[package]
name = "converlex"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
anyhow = "1.0.98"
rfd = "0.15.3"
tokio = { version = "1.44.2", features = ["full", "macros"] }
vizia = { git = "https://github.com/vizia/vizia" }
ez-ffmpeg = { version = "0.4", features = ["async"] }